
-- DROP FUNCTION UFN_PASS_ENCRIPT
CREATE FUNCTION [dbo].[UFN_PASS_ENCRIPT](@PASS VARCHAR(50)) RETURNS VARBINARY(8000) 
--
BEGIN
	
	DECLARE @D_PASS AS  VARBINARY(8000)

	SET @D_PASS = ENCRYPTBYPASSPHRASE('Encript0110', @PASS)

	RETURN @D_PASS

END


