CREATE TABLE [GFR].[tb_solicitante] (
    [id]                   INT             IDENTITY (1, 1) NOT NULL,
    [tipoSolicitanteId]    INT             NOT NULL,
    [solicitudId]          INT             NOT NULL,
    [nombres]              VARCHAR (50)    NULL,
    [apellidoPaterno]      VARCHAR (50)    NULL,
    [apellidoMaterno]      VARCHAR (50)    NULL,
    [razonSocial]          VARCHAR (250)   NULL,
    [tipoDocumentoId]      INT             NULL,
    [numeroDocumento]      VARCHAR (15)    NULL,
    [sexoId]               INT             NULL,
    [estadoCivilId]        INT             NULL,
    [fechaIniCargoAct]     DATETIME        NULL,
    [fechaFinCargoAct]     DATETIME        NULL,
    [nombreJefeDirecto]    VARCHAR (250)   NULL,
    [telefonoJefeDirecto]  VARCHAR (15)    NULL,
    [fechaConstitucion]    DATETIME        NULL,
    [actividadEconomica]   VARCHAR (250)   NULL,
    [numeroEmpleados]      INT             NULL,
    [montoIngresosAnuales] DECIMAL (18, 2) NULL,
    [ubigeoDireccion]      VARCHAR (6)     NULL,
    [direccion]            VARCHAR (250)   NULL,
    [email]                VARCHAR (50)    NULL,
    [telefono]             VARCHAR (15)    NULL,
    [institucionEducativa] VARCHAR (100)   NULL,
    [tituloObtenido]       VARCHAR (50)    NULL,
    [duracionEstudios]     INT             NULL,
    [idiomas]              VARCHAR (50)    NULL,
    [empresa]              VARCHAR (100)   NULL,
    [cargo]                VARCHAR (100)   NULL,
    [montoIngresosMes]     DECIMAL (18, 2) NULL,
    [montoGastosMes]       DECIMAL (18, 2) NULL,
    [observacion]          VARCHAR (250)   NULL,
    [auditoriaUC]          INT             NOT NULL,
    [auditoriaUM]          INT             NULL,
    [auditoriaFC]          DATETIME        NOT NULL,
    [auditoriaFM]          DATETIME        NULL,
    [fechaNacimiento]      SMALLDATETIME   NULL,
    [estado]               INT             NOT NULL,
    [quotaObjetivo]        DECIMAL (18)    NULL,
    CONSTRAINT [PK_Solicitante] PRIMARY KEY CLUSTERED ([id] ASC),
    CONSTRAINT [FK_Solicitante_Solicitud] FOREIGN KEY ([solicitudId]) REFERENCES [GFR].[tb_solicitud] ([id])
);

